name: Python lint

on:
  push:
    branches:
      - main
      - devel-*
  pull_request:
    branches: [ main ]

env:
  SEMGREP_RULES: >-  # https://semgrep.dev/explore
    p/security-audit
    p/secrets
    p/flask
    p/python

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
        cache: 'poetry'

    - name: Install with poetry
      run: |
        sudo apt update
        sudo apt install python3-dev  # for compiling things
        sudo apt install libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0  # For HTML -> PDF
        sudo apt install libreoffice-base-nogui libreoffice-calc-nogui libreoffice-draw-nogui libreoffice-impress-nogui libreoffice-math-nogui libreoffice-writer-nogui  # For Office -> PDF
        sudo apt install exiftool  # for extracting exif information
        python -m pip install --upgrade pip poetry
        poetry add -D flake8 pylint semgrep
        poetry install

    - name: bandit
      run: |
        poetry run bandit -r .
      if: ${{ always() }}

    - name: codespell
      uses: codespell-project/actions-codespell@master
      with:
        exclude_file: ./cache/cache.conf
        ignore_words_file: .codespellignore
      if: ${{ always() }}

    - name: flake8
      run: |
        poetry run flake8 . --show-source --statistics --exclude yara_repos
      if: ${{ always() }}

    - name: pylint
      run: |
        poetry run pylint -ry bin pandora tools website
      if: ${{ always() }}

    - name: semgrep
      run: |
        poetry run semgrep --config auto
      if: ${{ always() }}
