name: Python lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

      - name: Install test dependencies
        run: |
          python -m pip install flake8 black bandit mypy lxml pylint
      - name: black
        run: |
          black --diff --check .
        if: ${{ always() }}
      - name: flake8
        run: |
          flake8 . --show-source --statistics --max-line-length=120
        if: ${{ always() }}
      - name: pylint
        run: |
          pylint bin pandora website
        if: ${{ always() }}
