name: semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
