name: Python application - API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }} sample

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}

    - name: Cache kvrocks
      id: kvrocks
      uses: actions/cache@v3
      with:
        path: ../kvrocks
        key: ${{ runner.os }}-kvrocks

    - name: Clone Kvrocks
      uses: actions/checkout@v4
      with:
        repository: apache/kvrocks
        path: kvrocks-tmp
        ref: 2.5
        submodules: true

    - name: Install kvrocks
      run: |
        sudo apt-get update
        sudo apt-get install gcc g++ make libsnappy-dev autoconf automake libtool libgtest-dev
        mv kvrocks-tmp ../kvrocks
        pushd ..
        pushd kvrocks
        ./x.py build
        popd
        popd

    - name: Clone Redis
      uses: actions/checkout@v4
      with:
        repository: redis/redis
        path: redis-tmp
        ref: 7.2

    - name: Install redis
      run: |
        mv redis-tmp ../redis
        pushd ..
        pushd redis
        make
        popd
        popd

    - name: Install with poetry
      run: |
        sudo apt install python3-dev  # for compiling things
        sudo apt install libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0  # For HTML -> PDF
        sudo apt install libreoffice-base-nogui libreoffice-calc-nogui libreoffice-draw-nogui libreoffice-impress-nogui libreoffice-math-nogui libreoffice-writer-nogui  # For Office -> PDF
        sudo apt install exiftool  # for extracting exif information
        python -m pip install --upgrade pip poetry
        poetry install
        echo PANDORA_HOME=`pwd` > .env

    - name: Clone PyPandora
      uses: actions/checkout@v4
      with:
        repository: pandora-analysis/pypandora
        path: pypandora

    - name: Run API tests
      run: |
        poetry run start
        sleep 10
        pushd pypandora
        poetry install
        poetry run pytest tests/test_web.py
        popd

        poetry run stop

    - name: Test update script
      run: |
        poetry run update --yes
        sleep 30
        poetry run stop
